# Generated by Django 4.2.16 on 2024-11-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamsafar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='start_location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
